mod-name: NearFutureConstruction
package:
  include-dependencies: true  # Include dependencies in the package
  included-gamedata:
    - NearFutureConstruction
  included-support:  # Include these root-level files in packages
    - readme.txt
    - changelog.txt
dependencies:  # Configure dependencies
  ModuleManager:
    version: 4.2.3
    location: s3
  B9PartSwitch:
    version: 2.20.0
    location: s3
deploy:
  SpaceDock:
    enabled: true  # activate/deactivate this deployment script
    mod-id: 563  # The Spacedock mod ID for deployment
  CurseForge:
    enabled: true  # activate/deactivate this deployment script
    mod-id: 220675  # The CurseForge mod ID for deployment
  GitHub:
    enabled: true  # activate/deactivate this deployment script
